# Note, This template deploys a Webserver Load Balancer that exposes our Nginx Proxy services.
# Service : Nginx Service listen to port 80
# SSL Termination is at ELB
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template deploys an Webserver Load Balancers.
Parameters: 

  ServerEnv:
    Description: "Server Environment name."
    Type: "String"

  WEBALBSG:
    Description: "Select the Security Group to use for the ALB"
    Type: "AWS::EC2::SecurityGroup::Id"

  PublicSubnets:
    Description: "Subnets to launch instances into"
    Type: "List<AWS::EC2::Subnet::Id>"  

  VPC:
    Description: VPC 
    Type: "AWS::EC2::VPC::Id"  

Resources:

  WEBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  WEBLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Type: application
      Scheme: "internet-facing"
      SecurityGroups:
        - !Ref WEBALBSG
      Subnets: !Ref PublicSubnets

  WEBLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref WEBLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WEBTargetGroup      

# Output LoadBalancer
Outputs:
  WEBLoadBalancer:
    Description: "A reference to the Web Load Balancer"
    Value: !Ref "WEBLoadBalancer"
  WEBTargetGroup:
    Description: "A reference to the Web TargetGroup"
    Value: !Ref "WEBTargetGroup"  