---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template deploys one S3 bucket
Parameters: 

  #PMRegionAStorage:
    #Description: "A reference to the Region Archive Storage"
    #Type: "String"

  PMServerEnv:
    Description: "Server Environment name."
    ConstraintDescription: "Choose an Environment from the drop down"
    Type: "String"


Resources:

  ############################################################################
  # S3 Backup Bucket Data Bucket
  ############################################################################

  S3Backup:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "Private"
      VersioningConfiguration:
        Status: "Enabled"
      LifecycleConfiguration:
        Rules:
        - Id: "MyBackupArchive"
          Status: "Enabled"
          ExpirationInDays: '365' # Complete Disposal/Deletion of Data after 1 year
          Transition:
            TransitionInDays: '60' # Move Data from S3 bucket to Infrequent Archive/Glacier after 60 days.
            StorageClass: !Ref "PMRegionAStorage"
    DeletionPolicy: "Retain"

  S3BackupPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref "S3Backup"
      PolicyDocument:
        Statement:
        - Sid: "DenyUnEncryptedObjectUploads"
          Effect: "Deny"
          Principal:
            AWS: "*"
          Action: "s3:PutObject"
          Resource: !Join ["", ["arn:aws:s3:::", !Ref "S3Backup", "/*"]]
          Condition:
            StringNotEquals:
              s3:x-amz-server-side-encryption: "AES256"

Outputs:

  S3Backup:
    Description: "S3 Backup Bucket Name"
    Value: !Ref "S3Backup"