---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template describes a new IAM user. 
    Author: Philippe Traon <ptraon@pm.me>
Parameters:
  ServerEnv:
    Description: "Server Environment name."
    Type: "String"  

Resources:
  ################################## IAM USER #############################################

  ###### DOCUMENTATION ######
  # https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-iam-user.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-iam.html#scenario-iam-user
  ###########################    
  IAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: !Sub "${ServerEnv}-S3FullAccess"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource: "*"

  ################################## IAM ACCESS KEY #############################################

  ###### DOCUMENTATION ######
  # https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-iam-accesskey.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-iam.html#scenario-iam-accesskey
  ###########################   
  IAMUserCredentials:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref IAMUser