---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template creates a new S3 bucket. 
    Author: Philippe Traon <ptraon@pm.me>
Parameters:
  ServerEnv:
    Description: "Server Environment name."
    Type: "String"  

Resources:

  ################################## S3 BUCKET #############################################

  ###### DOCUMENTATION ######
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  ########################### 
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: s3bucketp10
      # AccessControl: PublicRead
   #DeletionPolicy: Retain

  ###### DOCUMENTATION ######
  # https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-iam-user.html
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-iam.html#scenario-iam-user
  ###########################    
  S3User:
    Type: 'AWS::IAM::User'
    Properties:
      Policies:
        - PolicyName: bucket-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource: "*" 

  S3UserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref S3User 

Outputs:
  AccessKeyID:
    Value: !Ref S3UserAccessKey
  SecretAccessKey:
    Value: !GetAtt S3UserAccessKey.SecretAccessKey
  BucketName:
    Value: !Ref S3Bucket
  User:
    Value: !Ref S3User                 