---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template contains the Security Groups. 
    Author: Philippe Traon <ptraon@pm.me>
Parameters:
  VPC:
    Description: VPC 
    Type: "AWS::EC2::VPC::Id"
  ServerEnv:
    Description: "Server Environment name."
    Type: "String"  
  MyIP:
    Description: "My own IP."
    Type: "String" 
  IPtoAllow:
    Description: "IP to allow."
    Type: "String"   

Resources:

  ###### SECURITY GROUPS ############

  ###### DOCUMENTATION ######
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
  # https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html
  # https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Security.html#VPC_Security_Comparison
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html
  # https://www.javatpoint.com/aws-nacl-vs-security-group
  ###########################

  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable HTTP, HTTPS, ICMP and SSH
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref MyIP  
      Tags:
        - Key: Name
          Value: EC2SG

  RDSSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC 
      GroupDescription: Enable 3306
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          SourceSecurityGroupId: !Ref EC2SG
      Tags:
        - Key: Name
          Value: RDSSG  

  ICMPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Groupe de Securite ICMP"
      GroupName: "ICMP-SG"
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Groupe de Securite SSH"
      GroupName: "SSH-SG"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC

  WebIntraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Groupe de Securite Web Intranet"
      GroupName: "SSH-WebIntra"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/31
      VpcId: !Ref VPC

  VPNSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Groupe de Securite VPN"
      GroupName: "VPN-SG"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 1194
          ToPort: 1194
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC               

Outputs:

  EC2SG: 
    Description: "A reference to the security group for EC2"
    Value: !Ref "EC2SG"

  RDSSG:
    Description: "A reference to the security group for RDS"
    Value: !Ref "RDSSG"  

  ICMPSecurityGroup: 
    Description: "A reference to the security group for ICMPSecurityGroup"
    Value: !Ref "ICMPSecurityGroup"
    
  SSHSecurityGroup: 
    Description: "A reference to the security group for SSHSecurityGroup"
    Value: !Ref "SSHSecurityGroup"
    
  WebIntraSecurityGroup: 
    Description: "A reference to the security group for WebIntraSecurityGroup"
    Value: !Ref "WebIntraSecurityGroup"
    
  VPNSecurityGroup: 
    Description: "A reference to the security group for VPNSecurityGroup"
    Value: !Ref "VPNSecurityGroup"         
             