---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template creates Intranet and VPN vai EC2 Instance. 
    Author: Philippe Traon <ptraon@pm.me>
Parameters:
  VPC:
    Description: VPC 
    Type: "AWS::EC2::VPC::Id"
  ServerEnv:
    Description: "Server Environment name."
    Type: "String"  
  MyIP:
    Description: "My own IP."
    Type: "String" 
  IPtoAllow:
    Description: "IP to allow."
    Type: "String"   
  InstanceType:
    Description: "The type of ec2 instance"
    Type: "String"   
  KeyName:
    Description: "Enter an existing EC2 KeyPair."
    Type: "String"   
  PublicSubnet3:
    Description: "Public subnet 3"
    Type: "AWS::EC2::Subnet::Id" 
  PrivateSubnet3:
    Description: "Private subnet 3"
    Type: "List<AWS::EC2::Subnet::Id>"     

Resources:
  VPNInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SourceDestCheck: false
      KeyName: !Ref SSHKeyName
      SubnetId: !Ref PublicSubnet3
      SecurityGroupIds: 
       - !GetAtt VPNCSG.GroupId
      UserData:
        !Base64
          Fn::Sub: |
            #!/bin/sh
            apt update 
            apt install openvpn -y
            sudo sysctl -w net.ipv4.ip_forward=1
          # echo 1 > /proc/sys/net/ipv4/ip_forward
            # masquerade persistent install
      ImageId: ami-035837f5f05288cef
      Tags:
      - Key: Name
        Value: !Sub '{ServerEnv}-OpenVPN'

  IntranetInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref PrivateSubnet3
      SecurityGroupIds: 
       - !GetAtt IntranetSG.GroupId
      Tags:
      - Key: Name
        Value: !Sub '${ServerEnv}-Intranet'
      UserData:
        !Base64
          Fn::Sub: |
            #!/bin/bash
            apt update
            apt install apache2 php php-mysql -y
            system start apache2
            echo "<h1>Intranet</h1>" >> /var/www/html/index.html 
      ImageId: ami-035837f5f05288cef     